name: Continuous Deployment

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publishing for {{ "${{ matrix.job.os " }}}}
    runs-on: {{ "${{ matrix.job.os " }}}}
    strategy:
      matrix:
        rust: [stable]
        job:
          - os: macos-latest
            os_name: macos
            target: x86_64-apple-darwin
            architecture: x86_64
            binary_postfix: ""
          - os: ubuntu-latest
            os_name: linux
            target: x86_64-unknown-linux-gnu
            architecture: x86_64
            binary_postfix: ""
          - os: windows-latest
            os_name: windows
            target: x86_64-pc-windows-msvc
            architecture: x86_64
            binary_postfix: ".exe"

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: {{ "${{ matrix.rust " }}}}
          profile: minimal
          override: true
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: {{ "${{ matrix.rust " }}}}
          args: --release --target {{ "${{ matrix.job.target " }}}}

      - name: Packaging final binary
        shell: bash
        run: |
          cd target/{{ "${{ matrix.job.target " }}}}/release
          BINARY_NAME={{project-name}}{{ "${{ matrix.job.binary_postfix " }}}}
          strip $BINARY_NAME

          RELEASE_NAME={{project-name}}-${GITHUB_REF/refs\/tags\//}-{{ "${{ matrix.job.os_name " }}}}-{{ "${{ matrix.job.architecture " }}}}
          tar czvf $RELEASE_NAME.tar.gz $BINARY_NAME

          if [[ {{ "${{ runner.os " }}}} == 'Windows' ]]; then
            certutil -hashfile $RELEASE_NAME.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
          else
            shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256
          fi
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/{{ "${{ matrix.job.target " }}}}/release/{{project-name}}-*.tar.gz
            target/{{ "${{ matrix.job.target " }}}}/release/{{project-name}}-*.sha256
        env:
          GITHUB_TOKEN: {{ "${{ secrets.GITHUB_TOKEN " }}}}

  publish-cargo:
    name: Publishing to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token {{ "${{ secrets.CARGO_API_KEY " }}}} --allow-dirty
